spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: CalendarApp

server:
  port: 8080
